# specialmobs:_family_of_skeletons.toml
# This config contains options that apply to the family of skeletons as a whole;
# that is, the vanilla replacement and all special variants.


# Category: general
# Options standard to all mob families (that is, not specific to any particular mob family).

	# Whether this mob family replaces vanilla skeletons with its vanilla replacement species.
	# The "master_vanilla_replacement" setting in the mod's main config must also be true for this to work.
	# <Boolean> Valid Values: { true, false }, Default: true
	general.vanilla_replacement = true

	# When greater than 0, skeletons will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for "master_random_scaling", though
	# species configs can override this value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.family_random_scaling = -1.0

	# The chance for skeletons to spawn as special variants.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.25
	general.special_variant_chance.base = 0.25
	# The chance for skeletons to spawn as special variants when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: [ "0.13 world_time < 120000", "0.5 moon_phase full & special_difficulty >= 0.5", "0.38 moon_phase full", "0.38 special_difficulty >= 0.5" ]
	#    Range for Values: 0.0 ~ 1.0
	general.special_variant_chance.exceptions = [
		"0.13 world_time < 120000",
		"0.5 moon_phase full & special_difficulty >= 0.5",
		"0.38 moon_phase full",
		"0.38 special_difficulty >= 0.5"
	]

	# The weight of each skeleton species to be chosen as the replacement when
	# skeletons spawn as special variants. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.brute.base = 60.0
	general.weight.fire.base = 60.0
	general.weight.gatling.base = 60.0
	general.weight.giant.base = 60.0
	general.weight.knight.base = 60.0
	general.weight.ninja.base = 60.0
	general.weight.poison.base = 60.0
	general.weight.sniper.base = 60.0
	general.weight.spitfire.base = 15.0
	general.weight.stray.base = 15.0
	general.weight.weathered.base = 60.0

	# The weight of each skeleton species to be chosen as the replacement when
	# skeletons spawn as special variants when specific environmental conditions are met. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.brute.exceptions = []
	general.weight.fire.exceptions = [
		"300.0 dimension_property ultrawarm",
		"300.0 temp > 1.0",
		"150.0 temp >= 0.8",
		"7.5 temp freezing",
		"300.0 biome minecraft:warm_ocean",
		"300.0 biome minecraft:deep_warm_ocean",
		"150.0 biome minecraft:lukewarm_ocean",
		"150.0 biome minecraft:deep_lukewarm_ocean",
		"15.0 biome minecraft:cold_ocean",
		"15.0 biome minecraft:deep_cold_ocean",
		"7.5 biome minecraft:deep_frozen_ocean"
	]
	general.weight.gatling.exceptions = []
	general.weight.giant.exceptions = [
		"300.0 terrain_depth >= 0.4",
		"300.0 y_from_sea > 25",
		"150.0 moon_phase new",
		"15.0 y_from_sea <= 0"
	]
	general.weight.knight.exceptions = []
	general.weight.ninja.exceptions = []
	general.weight.poison.exceptions = [
		"300.0 biome_category taiga",
		"300.0 biome_category jungle",
		"300.0 biome_category forest",
		"300.0 biome_category swamp",
		"300.0 biome minecraft:crimson_forest",
		"150.0 moon_phase full"
	]
	general.weight.sniper.exceptions = []
	general.weight.spitfire.exceptions = [
		"300.0 dimension_property ultrawarm",
		"300.0 temp > 1.0",
		"150.0 temp >= 0.8",
		"7.5 temp freezing",
		"300.0 biome minecraft:warm_ocean",
		"300.0 biome minecraft:deep_warm_ocean",
		"150.0 biome minecraft:lukewarm_ocean",
		"150.0 biome minecraft:deep_lukewarm_ocean",
		"15.0 biome minecraft:cold_ocean",
		"15.0 biome minecraft:deep_cold_ocean",
		"7.5 biome minecraft:deep_frozen_ocean"
	]
	general.weight.stray.exceptions = [
		"7.5 dimension_property ultrawarm",
		"300.0 temp freezing",
		"15.0 temp >= 0.8",
		"7.5 temp > 1.0",
		"300.0 biome minecraft:deep_frozen_ocean",
		"150.0 biome minecraft:cold_ocean",
		"150.0 biome minecraft:deep_cold_ocean",
		"15.0 biome minecraft:lukewarm_ocean",
		"15.0 biome minecraft:deep_lukewarm_ocean",
		"7.5 biome minecraft:warm_ocean",
		"7.5 biome minecraft:deep_warm_ocean"
	]
	general.weight.weathered.exceptions = [
		"300.0 dimension_property ultrawarm",
		"300.0 dimension_property natural & rainfall = 0.0",
		"7.5 terrain_depth <= 0.0",
		"7.5 rainfall > 0.85",
		"7.5 weather rain & position can_see_sky",
		"150.0 moon_brightness < 0.5"
	]


# Category: skeletons
# Options specific to the family of skeletons.

	# Chance for valid skeletons to spawn as babies. Baby mobs are about half-sized,
	# move 50% faster, drop 150% more experience, and are 50% cuter.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.05
	skeletons.baby_chance = 0.05
