# Please refer to the wiki page located at https:#github.com/TheComputerizer/Music-Triggers/wiki
# or the discord server located at https:#discord.gg/FZHXFYp8fc
# for any specific questions you might have regarding the main config file
[triggers]
		#Global Trigger Parameters
	[triggers.universal]
		# The number of ticks a trigger will be active for after its parameters are no longer met.
		persistence = "100"
		# The number of ticks it takes for a song to start playing when the trigger becomes active.
		trigger_delay = "300"
		# The number of ticks it takes for a trigger to be active for after its parameters are met.
		start_delay = "0"
		# The number of ticks it takes the first song of the trigger to fade in.
		fade_in = "100"
		# The number of ticks it takes the currently playing song to fade out when the trigger is no longer active.
		fade_out = "100"
		# The number of ticks it takes for a song to start playing after a song within the same pool finishes.
		song_delay = "1"
		# Dead
	[triggers.dead]
		#The numerical priority of a trigger. In the case of multiple triggers being able to play at once, the highest priority wins, unless REVERSE_PRIORITY is enabled.
		priority = "69"
		# Gamestage
	[triggers.gamestage]

	[triggers.menu]
		# 3600 to 600 because Main Menu should be have less delay.
		song_delay = "600"
		persistence = "600"

		# Overworld
	[[triggers.dimension]]
		identifier = "overworld"
		resource_name = [ "overworld" ]
		priority = "1"

		# Night
	[[triggers.time]]
		identifier = "night"
		start_hour = "14"
		end_hour = "24"
		priority = "1"

		# Day
	[[triggers.time]]
		identifier = "day"
		end_hour = "14"
		priority = "1"

		# Deep Dark
	[[triggers.dimension]]
		identifier = "deep_darky"
		resource_name = [ "deep_darky" ]
		priority = "1"

		# Nether
	[[triggers.dimension]]
		identifier = "nether"
		resource_name = [ "nether" ]
		priority = "1"

		# End
	[[triggers.dimension]]
		identifier = "end"
		resource_name = [ "end" ]
		priority = "1"

		# Stronghold
	[[triggers.structure]]
		identifier = "stronghold"
		resource_name = [ "stronghold" ]
		persistence = "300"
		fade_in = "300"
		fade_out = "300"
		priority = "9"
		song_delay = "3600"

		# Village
	[[triggers.structure]]
		identifier = "village"
		resource_name = [ "village" ]
		persistence = "300"
		fade_in = "300"
		fade_out = "300"
		priority = "5"
		song_delay = "1200"

		# Dragons
	[[triggers.mob]]
		identifier = "dragon"
		#A list of strings used for anything that needs to access a registry. It will be explained more in depth for the triggers that use it.
		resource_name = [ "dragon" "fire_dragon" "ice_dragon" "lightning_dragon" ]
		#The range in blocks a triggers that uses it will check. It will be explained more in depth for the triggers that use it.
		detection_range = "256"
		persistence = "300"
		fade_in = "300"
		fade_out = "300"
		priority = "10"
		song_delay = "1200"

		# Enderdragon
	[[triggers.mob]]
		identifier = "enderdragon"
		resource_name = [ "Ender Dragon" ]
		detection_range = "256"
		mob_targeting = true
		persistence = "300"
		fade_in = "300"
		fade_out = "300"
		priority = "10"
		song_delay = "1200"

		# Zombie
	#[[triggers.mob]]
		#	identifier = "basic"
		#	resource_name = [ "zombie" "skeleton" "creeper" "spider" "blaze" "pillager" "vindicator" "summoner" ]
		#	toggle_inactive_playable = true
		#	detection_range = "32"
		#	priority = "9"

[songs]
	# Global Volume Slider
	[songs.universal]
		volume = "0.5"
		play_once = true
		must_finish = true
	# Death
	# 60s of Blank Audio x3
	[songs.60]
		triggers = [ "dead" ]
	[songs.601]
		triggers = [ "dead" ]
	[songs.602]
		triggers = [ "dead" ]

		# Yoda Death Easter Egg
	[songs.yodadeath]
		triggers = [ "dead" ]
		# Lower Death Fade in to 0 since the deathscreen should be responsive.
		fade_in = "0"
		# Lower Death Fade out to 0 since the deathscreen should be responsive.
		fade_out = "0"
		# Determines whether triggers that are playable but not active will have their persistence timers get reset.
		passive_persistence = true
		# Determines if triggers that are playable but not active get toggled off
		toggle_inactive_playable = true
		# The song must finish playing before the trigger is able to change
		must_finish = false

		# Witcher 3 Death
	[songs.death]
		triggers = [ "dead" ]
		fade_in = "0"
		fade_out = "0"
		passive_persistence = true
		toggle_inactive_playable = true
		must_finish = false

		# 8bit Death
	[songs.death8bit]
		triggers = [ "dead" ]
		fade_in = "0"
		fade_out = "0"
		passive_persistence = true
		toggle_inactive_playable = true
		must_finish = false

		# oof
	[songs.oof]
		triggers = [ "dead" ]
		fade_in = "0"
		fade_out = "0"
		passive_persistence = true
		toggle_inactive_playable = true
		must_finish = false

		# itsjustaburningmemory
	[songs.itsjustaburningmemory]
		triggers = [ "dead" ]
		fade_in = "0"
		fade_out = "0"
		passive_persistence = true
		toggle_inactive_playable = true
		must_finish = false

		# Main Menu
	[songs.frozenintime]
		triggers = [ "menu" ]
		fade_in = "200"
		fade_out = "200"
		must_finish = false

	[songs.rememberingtheworldasitusedtobe]
		triggers = [ "menu" ]
		fade_in = "200"
		fade_out = "200"
		must_finish = false

		# Day
	# The Hermit [day]
	[songs.apokatastasisi]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.marchofthepriests]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.apokatastasisii]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.passing]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.thehermit]
		triggers = [ "time-day" "dimension-overworld" ]

	# Sea of Black [day]
	[songs.aesthetic]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.nekrosis]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.ecstaticparadigm]
		triggers = [ "time-day" "dimension-overworld" ]

	# Illuminato [day]
	[songs.heosphoros]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.illuminatio]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.thylight]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.sacrumnoctis]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.chaliceofeternity]
		triggers = [ "time-day" "dimension-overworld" ]

	# You Disappeared [day]
	[songs.abedofashes]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.afaintlightonthesurface]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.falseidols]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.quicksand]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.smokeandmirrors]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.thedaywhenyoulostyoursmile]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.threadbare]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.youdisappeared]
		triggers = [ "time-day" "dimension-overworld" ]

	# The Foundations of Ruin [day]
	[songs.aseductionofmalice]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.boundtomemory]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.deceivedbyshelter]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.entangledinmortar]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.hauntedbywhispers]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.inthecompanyofruin]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.lonesomehallsofruin]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.remnantsofthemissing]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.thecollectorsharvest]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.theeternalveil]
		triggers = [ "time-day" "dimension-overworld" ]
	[songs.themanifestation]
		triggers = [ "time-day" "dimension-overworld" ]

		# Night
		# 0 = Any moon phase
		# 1 = Full Moon
		# 2 = Waning Gibbous
		# 3 = Last Quarter
		# 4 = Waning Crescent
		# 5 = New Moon
		# 6 = Waxing Crescent
		# 7 = First Quarter
		# 8 = Waxing Gibbous
	# Darkwood (Original Video Game Soundtrack)
	[songs.intro]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.dream]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.baba]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.greenpeople]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.roadtohome]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "5"
	[songs.untitled1]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.firstvisit]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.heartbeat]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.piotrek]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.untitled2]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.wedding]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "1"
	[songs.untitled3]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.wolf]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.voices]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.lasthideout]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"

	# Criers Bane [night]
	[songs.atheatreofshadows]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.cursedridersofthenight]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.parlourofignorance]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.thecrossing]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.theunforgivingtolloffame]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.vagrantsouls]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.beyondthelimit]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"

	# Sleepy Town of Winter [night]
	[songs.adoorbeyondperception]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.coldsleuthing]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.eyesofblack]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.mindlesswanderftzenjungle]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.nothingbutdustftkimguy]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.strangersreflection]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.twilightreverie]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	[songs.twistoftime]
		triggers = [ "time-night" "dimension-overworld" ]
		moon_phase = "0"
	
		# Sunrise
	[songs.endofthenight]
		triggers = [ "time-not_set" "dimension-overworld" ]
		moon_phase = "0"
		time_bundle = "sunrise"

		# Nether
	# Echo [nether]
	[songs.whattheearthbore]
		triggers = ["dimension-nether"]
	[songs.thedeadfire]
		triggers = [ "dimension-nether"]
	[songs.burrows]
		triggers = [ "dimension-nether"]
	[songs.echo]
		triggers = [ "dimension-nether"]
	[songs.inanarchedworld]
		triggers = [ "dimension-nether"]
	[songs.omission]
		triggers = [ "dimension-nether"]
	[songs.eschatology]
		triggers = [ "dimension-nether"]
	[songs.drawnlikeamoth]
		triggers = [ "dimension-nether"]
	[songs.alldreamsmined]
		triggers = [ "dimension-nether"]
	# Onyx [nether]
	[songs.immemorial]
		triggers = [ "dimension-nether"]
	[songs.onesatoptheunknown]
		triggers = [ "dimension-nether"]
	[songs.nightsoclosetothetongue]
		triggers = [ "dimension-nether"]
	[songs.alonelystrain]
		triggers = [ "dimension-nether"]
	[songs.aphotic]
		triggers = [ "dimension-nether"]
	[songs.cavernofigneousflame]
		triggers = [ "dimension-nether"]
	[songs.onyx]
		triggers = [ "dimension-nether"]
	[songs.apalesignrevealed]
		triggers = [ "dimension-nether"]
	[songs.avenoir]
		triggers = [ "dimension-nether"]
	# End
	# Aftermath [end]
	[songs.ancientamulet]
		triggers = [ "dimension-end"]
	[songs.unveilingthescript]
		triggers = [ "dimension-end"]
	[songs.deepspacesignals]
		triggers = [ "dimension-end"]
	[songs.consternation]
		triggers = [ "dimension-end"]
	[songs.activating]
		triggers = [ "dimension-end"]
	[songs.iridescenceshimmer]
		triggers = [ "dimension-end"]
	[songs.theplanet]
		triggers = [ "dimension-end"]
	[songs.induction]
		triggers = [ "dimension-end"]
	[songs.nascency]
		triggers = [ "dimension-end"]
	# Edge of Solitude [end]
	[songs.roadtonowhere]
		triggers = [ "dimension-end"]
	[songs.solarhalos]
		triggers = [ "dimension-end"]
	[songs.beyondtheedge]
		triggers = [ "dimension-end"]
	[songs.echosphere]
		triggers = [ "dimension-end"]
	[songs.brokenworlds]
		triggers = [ "dimension-end"]
	[songs.losthorizon]
		triggers = [ "dimension-end"]
	[songs.overland]
		triggers = [ "dimension-end"]
	[songs.oceangrooves]
		triggers = [ "dimension-end"]
	# Cronosphere [end]
	[songs.reverseechoes]
		triggers = [ "dimension-nether"]
	[songs.deltazero]
		triggers = [ "dimension-nether"]
	[songs.spellbound]
		triggers = [ "dimension-nether"]
	[songs.intothevoid]
		triggers = [ "dimension-nether"]
	[songs.paralleldestiny]
		triggers = [ "dimension-nether"]
	[songs.ancientpillars]
		triggers = [ "dimension-nether"]
	[songs.particlestorm]
		triggers = [ "dimension-nether"]
	[songs.floatingspheres]
		triggers = [ "dimension-nether"]

	# Eternal Drift [nether]
	[songs.aphoticblack]
	triggers = [ "dimension-nether"]
	[songs.becomingonewithdarkness]
		triggers = [ "dimension-nether"]
	[songs.eternaldrift]
		triggers = [ "dimension-nether"]
	[songs.herebutnothere]
		triggers = [ "dimension-nether"]
	[songs.nebulousbeings]
		triggers = [ "dimension-nether"]
	[songs.surrender]
		triggers = [ "dimension-nether"]
	[songs.suspendedconsciousness]
		triggers = [ "dimension-nether"]
	[songs.theslowagonyofsolitude]
		triggers = [ "dimension-nether"]
	[songs.threnody]
		triggers = [ "dimension-nether"]

	# Sundown [end]
	[songs.chiaroscuro]
		triggers = [ "dimension-end"]
	[songs.ghostsmarchinghome]
		triggers = [ "dimension-end"]
	[songs.lastcall]
		triggers = [ "dimension-end"]
	[songs.livesinreverse]
		triggers = [ "dimension-end"]
	[songs.memoriesofanoldcity]
		triggers = [ "dimension-end"]
	[songs.nowayoutofthismaze]
		triggers = [ "dimension-end"]
	[songs.obscuration]
		triggers = [ "dimension-end"]
	[songs.relics]
		triggers = [ "dimension-end"]
	[songs.sundown]
		triggers = [ "dimension-end"]
	[songs.thedarkestnightever]
		triggers = [ "dimension-end"]
	[songs.theperilsofdawn]
		triggers = [ "dimension-end"]

	# The Last Resort [end]
	[songs.atransientshelter]
		triggers = [ "dimension-end"]
	[songs.latenightatthelastresort]
		triggers = [ "dimension-end"]
	[songs.opiateddreams]
		triggers = [ "dimension-end"]
	[songs.redcurtains]
		triggers = [ "dimension-end"]
	[songs.thedarknessbeforemyeyes]
		triggers = [ "dimension-end"]
	[songs.thesadnessofallthings]
		triggers = [ "dimension-end"]

	# The Desolation Age [deep dark]
	[songs.exodus]
		triggers = [ "dimension-deep_darky"]
	[songs.lightsout]
		triggers = [ "dimension-deep_darky"]
	[songs.paleconquerors]
		triggers = [ "dimension-deep_darky"]
	[songs.passageintooblivion]
		triggers = [ "dimension-deep_darky"]
	[songs.quietus]
		triggers = [ "dimension-deep_darky"]
	[songs.slowmotiondownfall]
		triggers = [ "dimension-deep_darky"]
	[songs.spectralparade]
		triggers = [ "dimension-deep_darky"]
	[songs.taintedcity]
		triggers = [ "dimension-deep_darky"]
	[songs.thedesolationage]
		triggers = [ "dimension-deep_darky"]

	# Invisible Cities [situational]
		# Unique to Enderdragons [end]
	[songs.thecelestialcity]
			triggers = [ "mob-enderdragon" ]
	[songs.onlystringsandtheirsupportsremain]
			triggers = [ "mob-enderdragon" ]
	[songs.totalperspectivevortex]
			triggers = [ "mob-enderdragon" ]

		# Unique to Dragons [overworld and nether]
	[songs.themerchantsofsevennations]
		triggers = [ "mob-dragon" ]
	[songs.nothingofthecitytouchestheearth]
		triggers = [ "mob-dragon" ]
	[songs.desiresarealreadymemories]
			triggers = [ "mob-dragon" ]
	[songs.everysolsticeequinox]
			triggers = [ "mob-dragon" ]

		# Unique to Strongholds [overworld]
	[songs.thedeadoutnumbertheliving]
			triggers = [ "dimension-overworld" "stronghold" ]
	[songs.thirteenthcenturytravelogue]
			triggers = [ "dimension-overworld" "stronghold" ]
	[songs.despairdialogue]
			triggers = [ "dimension-overworld" "stronghold" ]

		# Unique to Villages [overworld]
	[songs.sothatthecitycanbegintoexist]
			triggers = [ "dimension-overworld" "village" ]
	[songs.thedividedcity]
			triggers = [ "dimension-overworld" "village" ]