# specialmobs:_family_of_ghasts.toml
# This config contains options that apply to the family of ghasts as a whole;
# that is, the vanilla replacement and all special variants.


# Category: general
# Options standard to all mob families (that is, not specific to any particular mob family).

	# Whether this mob family replaces vanilla ghasts with its vanilla replacement species.
	# The "master_vanilla_replacement" setting in the mod's main config must also be true for this to work.
	# <Boolean> Valid Values: { true, false }, Default: true
	general.vanilla_replacement = true

	# When greater than 0, ghasts will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for "master_random_scaling", though
	# species configs can override this value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.family_random_scaling = -1.0

	# The chance for ghasts to spawn as special variants.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.25
	general.special_variant_chance.base = 0.25
	# The chance for ghasts to spawn as special variants when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: [ "0.13 world_time < 120000", "0.5 moon_phase full & special_difficulty >= 0.5", "0.38 moon_phase full", "0.38 special_difficulty >= 0.5" ]
	#    Range for Values: 0.0 ~ 1.0
	general.special_variant_chance.exceptions = [
		"0.13 world_time < 120000",
		"0.5 moon_phase full & special_difficulty >= 0.5",
		"0.38 moon_phase full",
		"0.38 special_difficulty >= 0.5"
	]

	# The weight of each ghast species to be chosen as the replacement when
	# ghasts spawn as special variants. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.baby.base = 0.0
	general.weight.corporeal_shift.base = 15.0
	general.weight.fighter.base = 60.0
	general.weight.king.base = 15.0
	general.weight.queen.base = 60.0
	general.weight.unholy.base = 15.0

	# The weight of each ghast species to be chosen as the replacement when
	# ghasts spawn as special variants when specific environmental conditions are met. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.baby.exceptions = []
	general.weight.corporeal_shift.exceptions = []
	general.weight.fighter.exceptions = []
	general.weight.king.exceptions = []
	general.weight.queen.exceptions = []
	general.weight.unholy.exceptions = []


# Category: ghasts
# Options specific to the family of ghasts.

	# If true, ghasts will be allowed to target any visible player in their follow range.
	# As of MC 1.8, vanilla ghasts can only start targeting players nearly completely horizontal from them.
	# <Boolean> Valid Values: { true, false }, Default: true
	ghasts.allow_vertical_targeting = true
