# specialmobs:queen_ghasts.toml
# This config contains options that apply only to the queen ghast species.


# Category: general
# Options standard to all mob species (that is, not specific to any particular mob species).

	# The chance for queen ghasts to succeed at natural spawn attempts. Does not affect Mob Replacement.
	# Note: Most species do NOT naturally spawn - they must be added by a mod or data pack for this option to do anything.
	# <Number> Range: 0.0 ~ 1.0, Default: 1.0
	general.natural_spawn_chance.base = 1.0
	# The chance for queen ghasts to succeed at natural spawn attempts when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: []
	#    Range for Values: 0.0 ~ 1.0
	general.natural_spawn_chance.exceptions = []

	# When greater than 0, queen ghasts will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for both "master_random_scaling" and
	# "family_random_scaling". The priority is species value > family value > master value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.random_scaling = -1.0

	# Attribute modifiers for queen ghasts. If no attribute changes are defined here, queen ghasts
	# will have the exact same attributes as their parent vanilla mob.
	# <Attribute List> Format: [ "namespace:attribute_name operation value", ... ], Default: [ "minecraft:generic.max_health + 20.0", "minecraft:generic.attack_damage + 2.0", "minecraft:generic.movement_speed * 0.6" ]
	#    Range for Values: Any Value
	general.attributes = [
		"minecraft:generic.max_health + 20.0",
		"minecraft:generic.attack_damage + 2.0",
		"minecraft:generic.movement_speed * 0.6"
	]

	# Subcategory: special_data
	# Special Mob Data. These are the values set to each queen ghast on spawn (in their NBT).

		# The amount of experience queen ghasts drop when killed by a player. Multiplied by 2.5 for babies.
		# Extra experience may drop based on equipment. Slime-style mobs also drop experience equal to slime size.
		# <Integer> Range: ≥ 0, Default: 7
		general.special_data.experience = 7
		# If greater than 0, queen ghasts will heal 1 half-heart of health every "heal_time" ticks. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 20
		general.special_data.heal_time = 20
		# Fall damage taken by queen ghasts is multiplied by this value. 0 is fall damage immunity.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.fall_damage_multiplier = 1.0
		# If true, queen ghasts will take no fire damage. Does not affect spawn restrictions.
		# <Boolean> Valid Values: { true, false }, Default: true
		general.special_data.immune_to_fire = true
		# If true, queen ghasts cannot be set on fire (this setting only matters if not immune to fire).
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_burning = false
		# If true, queen ghasts can breathe in water.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_drowning = false
		# If true, queen ghasts will ignore forces applied by flowing fluids.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fluid_push = false
		# If true, queen ghasts will be continuously damaged while wet.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.sensitive_to_water = false
		# If true, queen ghasts can be leashed. (Note: Leashed mobs can still attack you.)
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.allow_leashing = false
		# If true, queen ghasts will not trigger pressure plates.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_pressure_plates = false
		# Queen ghasts will not be 'trapped' in any blocks specified here (e.g. "cobweb" or "sweet_berry_bush").
		# <"minecraft:block" Registry List> Format: [ "namespace:entry_name", ... ], Default: []
		general.special_data.immune_to_sticky_blocks = []
		# Queen ghasts cannot be inflicted with any effects specified here (e.g. "instant_damage" or "regeneration").
		# <"minecraft:mob_effect" Registry List> Format: [ "namespace:entry_name", ... ], Default: []
		general.special_data.immune_to_effects = []

	# Subcategory: ranged_stats
	# Like Special Mob Data, these are set to NBT on spawn. Unlike SMD, ranged stats are not all applicable to all mobs.

		# The ranged attack spread (inaccuracy) for queen ghasts. 0 is perfect accuracy.
		# <Number> Range: ≥ 0.0, Default: 0.0
		general.special_data.ranged_attack.spread = 0.0
		# The delay (in ticks) for queen ghasts to perform a ranged attack from rest. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 20
		general.special_data.ranged_attack.charge_time = 20
		# The total delay (in ticks) queen ghasts wait between each ranged attack. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 60
		general.special_data.ranged_attack.refire_time = 60
		# The maximum distance (in blocks) at which queen ghasts can use their ranged attacks.
		# 0 disables ranged attacks.
		# <Number> Range: ≥ 0.0, Default: 64.0
		general.special_data.ranged_attack.max_range = 64.0


# Category: queen
# Options specific to queen ghasts.

	# The minimum and maximum (inclusive) number of babies queen ghasts spawn on death.
	# <Integer> Range: ≥ 0, Default: 3
	queen.babies.min = 3
	# <Integer> Range: ≥ 0, Default: 6
	queen.babies.max = 6

	# The minimum and maximum (inclusive) number of times queen ghasts can summon minions.
	# <Integer> Range: ≥ 0, Default: 4
	queen.summons.min = 4
	# <Integer> Range: ≥ 0, Default: 10
	queen.summons.max = 10
