# specialmobs:_family_of_magma_cubes.toml
# This config contains options that apply to the family of magma cubes as a whole;
# that is, the vanilla replacement and all special variants.


# Category: general
# Options standard to all mob families (that is, not specific to any particular mob family).

	# Whether this mob family replaces vanilla magma cubes with its vanilla replacement species.
	# The "master_vanilla_replacement" setting in the mod's main config must also be true for this to work.
	# <Boolean> Valid Values: { true, false }, Default: true
	general.vanilla_replacement = true

	# When greater than 0, magma cubes will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for "master_random_scaling", though
	# species configs can override this value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.family_random_scaling = -1.0

	# The chance for magma cubes to spawn as special variants.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.33
	general.special_variant_chance.base = 0.33
	# The chance for magma cubes to spawn as special variants when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: [ "0.17 world_time < 120000", "0.66 moon_phase full & special_difficulty >= 0.5", "0.5 moon_phase full", "0.5 special_difficulty >= 0.5" ]
	#    Range for Values: 0.0 ~ 1.0
	general.special_variant_chance.exceptions = [
		"0.17 world_time < 120000",
		"0.66 moon_phase full & special_difficulty >= 0.5",
		"0.5 moon_phase full",
		"0.5 special_difficulty >= 0.5"
	]

	# The weight of each magma cube species to be chosen as the replacement when
	# magma cubes spawn as special variants. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.bouncing.base = 60.0
	general.weight.hardened.base = 15.0
	general.weight.sticky.base = 60.0
	general.weight.volatile.base = 60.0

	# The weight of each magma cube species to be chosen as the replacement when
	# magma cubes spawn as special variants when specific environmental conditions are met. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.bouncing.exceptions = []
	general.weight.hardened.exceptions = []
	general.weight.sticky.exceptions = []
	general.weight.volatile.exceptions = []
