# specialmobs:dark_creepers.toml
# This config contains options that apply only to the dark creeper species.


# Category: general
# Options standard to all mob species (that is, not specific to any particular mob species).

	# The chance for dark creepers to succeed at natural spawn attempts. Does not affect Mob Replacement.
	# Note: Most species do NOT naturally spawn - they must be added by a mod or data pack for this option to do anything.
	# <Number> Range: 0.0 ~ 1.0, Default: 1.0
	general.natural_spawn_chance.base = 1.0
	# The chance for dark creepers to succeed at natural spawn attempts when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: []
	#    Range for Values: 0.0 ~ 1.0
	general.natural_spawn_chance.exceptions = []

	# When greater than 0, dark creepers will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for both "master_random_scaling" and
	# "family_random_scaling". The priority is species value > family value > master value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.random_scaling = -1.0

	# Attribute modifiers for dark creepers. If no attribute changes are defined here, dark creepers
	# will have the exact same attributes as their parent vanilla mob.
	# <Attribute List> Format: [ "namespace:attribute_name operation value", ... ], Default: []
	#    Range for Values: Any Value
	general.attributes = []

	# Subcategory: special_data
	# Special Mob Data. These are the values set to each dark creeper on spawn (in their NBT).

		# The amount of experience dark creepers drop when killed by a player. Multiplied by 2.5 for babies.
		# Extra experience may drop based on equipment. Slime-style mobs also drop experience equal to slime size.
		# <Integer> Range: ≥ 0, Default: 6
		general.special_data.experience = 6
		# If greater than 0, dark creepers will heal 1 half-heart of health every "heal_time" ticks. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 0
		general.special_data.heal_time = 0
		# Fall damage taken by dark creepers is multiplied by this value. 0 is fall damage immunity.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.fall_damage_multiplier = 1.0
		# If true, dark creepers will take no fire damage. Does not affect spawn restrictions.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fire = false
		# If true, dark creepers cannot be set on fire (this setting only matters if not immune to fire).
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_burning = false
		# If true, dark creepers can breathe in water.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_drowning = false
		# If true, dark creepers will ignore forces applied by flowing fluids.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fluid_push = false
		# If true, dark creepers will be continuously damaged while wet.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.sensitive_to_water = false
		# If true, dark creepers can be leashed. (Note: Leashed mobs can still attack you.)
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.allow_leashing = false
		# If true, dark creepers will not trigger pressure plates.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_pressure_plates = false
		# Dark creepers will not be 'trapped' in any blocks specified here (e.g. "cobweb" or "sweet_berry_bush").
		# <"minecraft:block" Registry List> Format: [ "namespace:entry_name", ... ], Default: []
		general.special_data.immune_to_sticky_blocks = []
		# Dark creepers cannot be inflicted with any effects specified here (e.g. "instant_damage" or "regeneration").
		# <"minecraft:mob_effect" Registry List> Format: [ "namespace:entry_name", ... ], Default: []
		general.special_data.immune_to_effects = []


# Category: creepers
# Options standard to all creepers.

	# Chance for dark creepers to spawn charged during thunderstorms.
	# If this is set to a non-negative value, it overrides the value set for "family_storm_charge_chance".
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	creepers.storm_charge_chance = -1.0

	# If true, dark creepers can explode while wet (normal creeper behavior).
	# <Boolean> Valid Values: { true, false }, Default: true
	creepers.can_explode_while_wet = true
	# If true, dark creepers will explode while burning. If extinguished before the fuse runs
	# out, they will resume normal behavior.
	# <Boolean> Valid Values: { true, false }, Default: false
	creepers.explodes_while_burning = false
	# If true, dark creepers will explode when hit by an indirect attack (e.g. an arrow).
	# <Boolean> Valid Values: { true, false }, Default: false
	creepers.explodes_when_shot = false
