
[version_check]
	#If enabled, the player will receive an in-game message when a new mod update is released.
	sendUpdateMessage = true

[difficulty]
	#If enabled, world difficulty will increased by the configured multiplier
	multiplayerDifficultyScaling = true
	#Only relevant if multiplayer difficulty scaling is enabled. For example, a value of 0.05 will apply an additional +5% difficulty increment per online player (If only one player is online this multiplier will not be active)
	#Range: 0.0 ~ 10.0
	difficultyMultiplayerRateMult = 0.0
	#Sets the multiplier used to increase world difficulty when players sleep through a night or thunderstorm.
	#Range: 1.0 ~ 1000.0
	sleepPenalty = 2.0
	#A list of dimensions that should give difficulty penalty. Difficulty increases more in these dimensions.
	dimensionPenaltyList = ["minecraft:the_nether", "minecraft:the_end", "minecraft:the_end", "dead_guys_untitled_deep_dark_:deep_darky"]
	#The difficulty rate multiplier used when a player enters a dimension with difficulty penalty.
	#Range: 0.0 ~ 1000.0
	dimensionPenalty = 0.5
	#(Currently unused) If enabled, players that are close to each other will have the average of their difficulty added together used instead of the nearby player with the highest difficulty.
	averageGroupDifficulty = false

	#A list of mobs that can only start spawning naturally when the nearest player has reached a certain difficulty
	[difficulty.mobDifficulties]
		40 = "apocalypse:fearwolf"

#This section revolves around everything related to the full moon sieges.
[full_moon]
	#How many levels of difficulty must pass before the additional full moon mob counts increases. For example, a value of 30.5 will increase the number of full moon mobs spawning during sieges for every 30.5 levels of difficulty passed.
	#Range: 0.1 ~ 100000.0
	difficultyUntilNextIncrease = 100000
	#If enabled, all full moon mobs spawned for a specific player will despawn if the player dies, which can help prevent spawn killing.
	despawnMobsOnDeath = true

	#The difficulty at which a specific type of full moon mob can start to spawn during sieges (It might be smart to let at least one type spawn at 0).
	[full_moon.spawn_start_difficulties]
		#Range: 0 ~ 100000
		breecher = 0
		#Range: 0 ~ 100000
		ghost = 100000
		#Range: 0 ~ 100000
		destroyer = 100000
		#Range: 0 ~ 100000
		seeker = 100000
		#Range: 0 ~ 100000
		grump = 420

	#The additional amount of a specific full moon mob that can spawn during a full moon siege. Increases with difficulty.
	[full_moon.additional_spawn_count]
		#Range: 0.0 ~ 100.0
		breecher = 0.0
		#Range: 0.0 ~ 100.0
		ghost = 0.0
		#Range: 0.0 ~ 100.0
		destroyer = 0.0
		#Range: 0.0 ~ 100.0
		seeker = 0.0
		#Range: 0.0 ~ 100.0
		grump = 0.0

	#The minimum amount of a specific full moon mob that can spawn during a full moon siege.
	[full_moon.min_spawn_count]
		#Range: 0 ~ 100
		breecher = 0
		#Range: 0 ~ 100
		ghost = 0
		#Range: 0 ~ 100
		destroyer = 0
		#Range: 0 ~ 100
		seeker = 0
		#Range: 0 ~ 100
		grump = 0

	#The maximum amount of a specific full moon mob that can spawn during a full moon siege. Keep in mind that since the additional moon mob count increases over time, these values should be carefully considered. Too many mobs will definitely cause problems.
	[full_moon.max_spawn_count]
		#Range: 0 ~ 100
		breecher = 0
		#Range: 0 ~ 100
		ghost = 0
		#Range: 0 ~ 100
		destroyer = 0
		#Range: 0 ~ 100
		seeker = 0
		#Range: 0 ~ 100
		grump = 0

[attributes]
	#If enabled, only hostile mobs will be given attribute bonuses and potion effects.
	mobsOnly = true

	[attributes.health]
		#A list of entity types that do not gain any health bonuses. Empty by default. Example: ["minecraft:creeper", "abundance:screecher"]
		healthBlacklist = []
		#The flat bonus gained from a full moon. Default is 10.0 (+10 hearts on full moons).
		#Range: 0.0 ~ 10000.0
		healthLunarFlatBonus = 0.0
		#The multiplier bonus gained from a full moon in percentage. Default is 0.5 (+50% on full moons)
		#Range: 0.0 ~ 10000.0
		healthLunarMultBonus = 0.0
		#The difficulty value for each application of the below values.
		#Range: 0.1 ~ 10000.0
		healthTimeSpan = 0.1
		#The flat bonus given each "_time_span" days.
		#Range: 0.0 ~ 10000.0
		healthFlatBonus = 0.0
		#The maximum flat bonus that can be given over time. Default is -1.0 (no limit).
		#Range: -1.0 ~ 10000.0
		healthFlatBonusMax = 0.0
		#The multiplier bonus given for each "_time_span" days. Default is 0.8 (+80%).
		#Range: 0.0 ~ 10000.0
		healthMultBonus = 0.0
		#The maximum multiplier bonus that can be given over time. Default is -1.0 (no limit).
		#Range: -1.0 ~ 10000.0
		healthMultBonusMax = 0.0

	[attributes.damage]
		#A list of entity types that do not gain any damage bonuses. Empty by default. Example: ["minecraft:creeper", "abundance:screecher"]
		damageBlacklist = []
		#The flat bonus gained from a full moon. Default is 1.0 (+1 damage on full moons).
		#Range: 0.0 ~ 10000.0
		damageLunarFlatBonus = 0.0
		#The multiplier bonus gained from a full moon. Default is 0.2 (+20% on full moons).
		#Range: 0.0 ~ 10000.0
		damageLunarMultBonus = 0.0
		#The difficulty value for each application of the below values.
		#Range: 0.1 ~ 10000.0
		damageTimeSpan = 0.1
		#The flat bonus given each "_time_span" days. Default is 1.0 (+1 damage)
		#Range: 0.0 ~ 10000.0
		damageFlatBonus = 0.0
		#The maximum flat bonus that can be given over time. Default is -1.0 (no limit).
		#Range: -1.0 ~ 10000.0
		damageFlatBonusMax = -0.0
		#The multiplier bonus given for each "_time_span" days. Default is 0.3 (+30%).
		#Range: 0.0 ~ 10000.0
		damageMultBonus = 0.0
		#The maximum multiplier bonus that can be given over time. Default is 5.0 (+500%).
		#Range: -1.0 ~ 10000.0
		damageMultBonusMax = 0.0

	[attributes.movement_speed]
		#A list of entity types that do not gain any speed bonuses. Empty by default. Example: ["minecraft:creeper", "abundance:screecher"]
		speedBlacklist = []
		#The multiplier bonus gained from a full moon in percentage. Default is 0.1 (+10% during full moons)
		#Range: 0.0 ~ 1000.0
		speedLunarMultBonus = 0.0
		#The difficulty value for each application of speed related values.
		#Range: 0.1 ~ 10000.0
		speedTimeSpan = 0.1
		#The multiplier bonus given for each "_time_span" days. Default is 0.05 (+5%).
		#Range: 0.0 ~ 10000.0
		damageMultBonus = 0.0
		#The maximum multiplier bonus that can be given over time. Default is 0.2 (+20%).
		#Range: -1.0 ~ 10000.0
		damageMultBonusMax = 0.0

	[attributes.knockback_resistance]
		#A list of entity types that do not gain any knockback resistance bonuses. Empty by default. Example: ["minecraft:creeper", "abundance:screecher"]
		KnockbackResistanceBlacklist = []
		#The flat bonus gained from a full moon in percentage. Default is 0.2 (+20% on full moons)
		#Range: 0.0 ~ 10000.0
		knockbackResLunarFlatBonus = 0.0
		#The difficulty value for each application of knockback resistance related values.
		#Range: 0.1 ~ 10000.0
		knockbackResTimeSpan = 0.1
		#The flat bonus given each "_time_span" days. Default is 0.05 (+5%).
		#Range: 0.0 ~ 10000.0
		knockbackResFlatBonus = 0.0
		#The maximum flat bonus that can be given over time. Default is 0.3 (+30%).
		#Range: -1.0 ~ 10000.0
		knockbackResFlatBonusMax = 0.0

[potion_effects]
	#The difficulty value for each application of weapon related values.
	#Range: 0.0 ~ 10000.0
	potionEffectTimeSpan = 0.0
	#The chance that a mob will be given a potion effect when it spawns. This value increases in accordance to potionEffectTimeSpan.
	#Range: 0.0 ~ 1.0
	potionEffectChance = 0.0
	#The additional chance gained from a full moon. Default is 0.2 (+20% chance on full moon).
	#Range: 0.0 ~ 1.0
	potionEffectLunarChance = 0.0
	#The maximum potion effect chance that can be given over time. Default is 0.95 (95% chance).
	#Range: 0.0 ~ 1.0
	potionEffectMaxChance = 0.0

	#A list of potion effects that mobs can spawn with. Each potion effect in the list has a difficulty unlock and an optional list of mobs that should not be given the effect.
	[potion_effects.potionEffectList]
		"minecraft:fire_resistance 5" = ["minecraft:magma_cube", "minecraft:zombified_piglin", "minecraft:blaze", "minecraft:ghast", "minecraft:strider"]
		"minecraft:strength 60" = ["apocalypse:ghost"]
		"minecraft:regeneration 30" = ["minecraft:wither", "minecraft:ender_dragon"]
		"minecraft:resistance 100" = ["apocalypse:ghost"]

[misc]
	#A list of blocks that the destroyer cannot explode. Generally speaking this list should be empty since destroyers are supposed to destroy any block, but if an exception is absolutely needed, the block in question can be whitelisted here.
	destroyerProofBlocks = ["minecraft:spawner", "minecraft:barrier", "minecraft:bedrock", "minecraft:obsidian", "minecraft:crying_obsidian", "minecraft:water", "minecraft:lava", "minecraft:cobblestone", "minecraft:stone"]
	#This is the chance in percentage for grumps to spawn with a bucket helmet equipped. Grumps with bucket helmets are heavily armored against arrows.
	#Range: 0.0 ~ 1.0
	grumpBucketHelmetChance = 1.0
	#The explosion power of Seeker fireballs.
	#Range: 1 ~ 10
	seekerExplosionPower = 4
	#The explosion power of Destroyer fireballs.
	#Range: 1 ~ 10
	destroyerExplosionPower = 2
	#If enabled, Destroyers will attempt to blow up their target player's respawn point (bed, respawn anchor etc.). This does not apply to the global respawn point (where players respawn if they have no bed etc.)
	destroyerTargetRespawnPos = false
	#Additional damage destroyer fireballs deals to its target's equipment (armor, shield etc.). Set this to 0 to deal no extra damage.
	#Range: > 0
	destroyerEquipmentDamage = 50
	#Useful if you want your players to be unable to just skip through full moons by disconnecting.
	pauseDaylightCycle = true

[compat]
	#(Option for TheOneProbe) If enabled, difficulty can only be seen when the probe is in extended mode.
	requireExtendedProbe = true

[acid_rain]
	#The chance of triggering an Acid Rain event when it starts raining. 1 = 100% chance, 0.5 = 50% etc. Defaults to 0.33 (roughly 1/3 chance).
	#Range: 0.0 ~ 1.0
	acidRainChance = 0.33
	#Determines the interval in which acid rain damage should be dealt in seconds. A value of 2 will inflict acid rain damage on players every 2 seconds.
	#Range: 1 ~ 1000
	rainTickRate = 3
	#The amount of damage that should be dealt to players on acid rain tick.
	#Range: 1 ~ 10000
	rainDamage = 1
	#Set to false to disable acid rain damage, or to true to turn it on.
	enableRainDamage = true

[equipment]
	#A list of entity types that can be given weapons.
	canHaveWeapons = ["minecraft:zombie", "minecraft:zombie_villager", "minecraft:drowned", "minecraft:husk", "minecraft:wither_skeleton", "minecraft:piglin", "minecraft:zombified_piglin", "minecraft:piglin_brute", "minecraft:vindicator"]
	#The difficulty value for each application of weapon related values.
	#Range: 0.0 ~ 10000.0
	weaponsTimeSpan = 30.0
	#The chance that a mob will be given a weapon when it spawns. This value increases in accordance to weaponsTimeSpan.
	#Range: 0.0 ~ 1.0
	weaponsChance = 0.05
	#The additional chance gained from a full moon. Default is 0.2 (+20% chance on full moon).
	#Range: 0.0 ~ 1.0
	weaponsLunarChance = 0.2
	#The maximum weapon chance that can be given over time. Default is 0.95 (95% chance).
	#Range: 0.0 ~ 1.0
	weaponsMaxChance = 0.95
	#If enabled, only weapons from the most recently unlocked weapon tier will be given to mobs. When disabled, a random weapon will be picked from all unlocked tiers.
	useCurrentWeaponTierOnly = false
	#A list of entity types that can be given armor.
	canHaveArmor = ["minecraft:zombie", "minecraft:zombie_villager", "minecraft:skeleton", "minecraft:drowned", "minecraft:husk", "minecraft:stray", "minecraft:wither_skeleton", "minecraft:piglin", "minecraft:zombified_piglin", "minecraft:piglin_brute"]
	#The difficulty value for each application of armor related values.
	#Range: 0.0 ~ 10000.0
	armorTimeSpan = 30.0
	#The chance that a mob will be given armor when it spawns. This value increases in accordance to armorTimeSpan.
	#Range: 0.0 ~ 1.0
	armorChance = 0.05
	#The additional chance gained from a full moon. Default is 0.2 (+20% chance on full moon).
	#Range: 0.0 ~ 1.0
	armorLunarChance = 0.2
	#The maximum armor chance that can be given over time. Default is 0.95 (95% chance).
	#Range: 0.0 ~ 1.0
	armorMaxChance = 0.95
	#If enabled, only armor from the most recently unlocked armor tier will be given to mobs. When disabled, random armor pieces will be picked from all unlocked tiers.
	useCurrentArmorTierOnly = false

	#A list of weapon items that mobs can spawn with, divided into tiers. Each tier group is paired with a difficulty that decides when mobs can start spawning with a weapon from the given tier group.
	[equipment.weaponLists]
		10 = ["minecraft:wooden_shovel", "minecraft:wooden_axe", "minecraft:wooden_pickaxe", "minecraft:wooden_sword"]
		20 = ["minecraft:stone_shovel", "minecraft:stone_axe", "minecraft:stone_pickaxe", "minecraft:stone_sword"]
		40 = ["minecraft:golden_shovel", "minecraft:golden_axe", "minecraft:golden_pickaxe", "minecraft:golden_sword"]
		60 = ["minecraft:iron_shovel", "minecraft:iron_axe", "minecraft:iron_pickaxe", "minecraft:iron_sword"]
		100 = ["minecraft:diamond_shovel", "minecraft:diamond_axe", "minecraft:diamond_pickaxe", "minecraft:diamond_sword", "minecraft:trident"]
		150 = ["minecraft:netherite_shovel", "minecraft:netherite_axe", "minecraft:netherite_pickaxe", "minecraft:netherite_sword"]

	#A list of armor items that mobs can spawn with, divided into tiers. Each tier group is paired with a difficulty that decides when mobs can start spawning with armor from the given tier group.
	[equipment.armorList]
		10 = ["minecraft:leather_boots", "minecraft:leather_leggings", "minecraft:leather_chestplate", "minecraft:leather_helmet", "minecraft:carved_pumpkin"]
		25 = ["minecraft:chainmail_boots", "minecraft:chainmail_leggings", "minecraft:chainmail_chestplate", "minecraft:chainmail_helmet", "apocalypse:bucket_helm"]
		40 = ["minecraft:golden_boots", "minecraft:golden_leggings", "minecraft:golden_chestplate", "minecraft:golden_helmet", "minecraft:turtle_helmet"]
		60 = ["minecraft:iron_boots", "minecraft:iron_leggings", "minecraft:iron_chestplate", "minecraft:iron_helmet"]
		100 = ["minecraft:diamond_boots", "minecraft:diamond_leggings", "minecraft:diamond_chestplate", "minecraft:diamond_helmet"]
		150 = ["minecraft:netherite_boots", "minecraft:netherite_leggings", "minecraft:netherite_chestplate", "minecraft:netherite_helmet"]

