
[in_game_gui]
	#Determines the base X position on the screen where the world difficulty count should render
	#Allowed Values: MIDDLE, RIGHT, LEFT
	difficultyRenderPosWidth = "LEFT"
	#Determines the base Y position on the screen where the world difficulty count should render
	#Allowed Values: MIDDLE, TOP, BOTTOM
	difficultyRenderPosHeight = "TOP"
	#Additional X offset for where to render difficulty in-game
	#Range: -10000 ~ 10000
	difficultyRenderXOffset = 2
	#Additional Y offset for where to render difficulty in-game
	#Range: -10000 ~ 10000
	difficultyRenderYOffset = 15
	#Toggles difficulty being rendered when the player is in creative mode.
	renderDifficultyInCreative = true
	#If enabled, difficulty will only be displayed if the Apocalypse difficulty keybind is pressed.
	keybindOnly = false

[world_config_button]
	#Determines the base X position of the Apocalypse world config button.
	#Allowed Values: MIDDLE, RIGHT, LEFT
	worldConfigButtonPosWidth = "MIDDLE"
	#Determines the base Y position of the Apocalypse world config button.
	#Allowed Values: MIDDLE, TOP, BOTTOM
	worldConfigButtonPosHeight = "TOP"
	#Additional X offset.
	#Range: -10000 ~ 10000
	worldConfigButtonXOffset = 175
	#Additional Y offset.
	#Range: -10000 ~ 10000
	worldConfigButtonYOffset = 100

[acid_rain_properties]
	#Decides the color to be used for acid rain. Must be hex color. Keep in mind that the color of the rain texture itself will "mix" with this setting.
	rainColor = "#ACFF75"
	#Decides the color to be used for snow during acid rain. Must be hex color. Keep in mind that the color of the snow texture itself will "mix" with this setting.
	snowColor = "#52FF3F"

