
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 575235
	#The name of the modpack
	modpackName = "Blood N Wine 2"
	#The version of the modpack
	modpackVersion = "2.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

