
[ConfigurableConflicts]
	#Format: 'minecraft:infinity;minecraft:mending', that will make this two enchantments compatible
	enchantmentsToBeAlwaysIncompatible = []
	enchantmentsToBeAlwaysCompatible = []

