
[General]
	#If the mod should only run on dedicated servers. When enabled it's not sent when in a singleplayer world.
	onlyRunOnDedicatedServers = true
	#Whether an empty line should be send before to first message to separate the welcome from other chat messages that might be sent.
	sendEmptyLineBeforeFirstMessage = true
	#The first message a player will receive when joining the world. Can be left empty.
	messageOneText = "Death welcomes you."
	#0: black, 1: dark_blue, 2: dark_green, 3: dark_aqua, 4: dark_red, 5: dark_purple, 6: gold, 7: gray, 8: dark_gray, 9: blue, 10: green, 11: aqua, 12: red, 13: light_purple, 14: yellow, 15: white
	#Range: 0 ~ 15
	messageOneColourIndex = 4
	#If a link is entered here, the complete message will be clickable.
	messageOneOptionalURL = "https://www.youtube.com/watch?v=Ugiw4zsXbvs"
	#The second message a player will receive when joining the world. Can be left empty.
	messageTwoText = "BNW2 Discord (click me)"
	#0: black, 1: dark_blue, 2: dark_green, 3: dark_aqua, 4: dark_red, 5: dark_purple, 6: gold, 7: gray, 8: dark_gray, 9: blue, 10: green, 11: aqua, 12: red, 13: light_purple, 14: yellow, 15: white
	#Range: 0 ~ 15
	messageTwoColourIndex = 6
	#If a link is entered here, the complete message will be clickable.
	messageTwoOptionalURL = "https://discord.gg/aDSV4bb"
	#The third message a player will receive when joining the world. Can be left empty.
	messageThreeText = "Good luck ;)"
	#0: black, 1: dark_blue, 2: dark_green, 3: dark_aqua, 4: dark_red, 5: dark_purple, 6: gold, 7: gray, 8: dark_gray, 9: blue, 10: green, 11: aqua, 12: red, 13: light_purple, 14: yellow, 15: white
	#Range: 0 ~ 15
	messageThreeColourIndex = 7
	#If a link is entered here, the complete message will be clickable.
	messageThreeOptionalURL = "https://www.youtube.com/watch?v=yBLdQ1a4-JI"

