
[General]
	#When enabled, uses the overworldBorderCoords to set the border.
	enableCustomOverworldBorder = false
	#When enabled, uses the netherBorderCoords to set the border.
	enableCustomNetherBorder = false
	#When enabled, uses the endBorderCoords to set the border.
	enableCustomEndBorder = false
	#When enabled, instead of teleporting the player inside near where they were, teleports them from the positive to the negative x/z coord and vice versa.
	shouldLoopToOppositeBorder = false
	#The amount of blocks the player is teleported inside after hitting the border.
	#Range: 0 ~ 1000
	distanceTeleportedBack = 10
	#The message which will be sent to the player when they are within 'distanceTeleportedBack' to the world border.
	nearBorderMessage = "You're getting close to the world border!"
	#The message which will be sent to the player when they hit the world border.
	hitBorderMessage = "You've hit the world border, and were teleported inside!"
	#The message sent to the player when they hit the border and 'shouldLoopToOppositeBorder' is enabled.
	loopBorderMessage = "You've hit the world border, and have looped around the world!"

[Borders]
	#The overworld border located at the positive x coordinate.
	#Range: 0 ~ 100000
	overworldBorderPositiveX = 100000
	#The overworld border located at the negative x coordinate.
	#Range: -100000 ~ 0
	overworldBorderNegativeX = -100000
	#The overworld border located at the positive z coordinate.
	#Range: 0 ~ 100000
	overworldBorderPositiveZ = 100000
	#The overworld border located at the negative z coordinate.
	#Range: -100000 ~ 0
	overworldBorderNegativeZ = -100000
	#The nether border located at the positive x coordinate.
	#Range: 0 ~ 100000
	netherBorderPositiveX = 12500
	#The nether border located at the negative x coordinate.
	#Range: -100000 ~ 0
	netherBorderNegativeX = -12500
	#The nether border located at the positive z coordinate.
	#Range: 0 ~ 100000
	netherBorderPositiveZ = 12500
	#The nether border located at the negative z coordinate.
	#Range: -100000 ~ 0
	netherBorderNegativeZ = -12500
	#The end border located at the positive x coordinate.
	#Range: 0 ~ 100000
	endBorderPositiveX = 12500
	#The end border located at the negative x coordinate.
	#Range: -100000 ~ 0
	endBorderNegativeX = -12500
	#The end border located at the positive z coordinate.
	#Range: 0 ~ 100000
	endBorderPositiveZ = 12500
	#The end border located at the negative z coordinate.
	#Range: -100000 ~ 0
	endBorderNegativeZ = -12500

