
[General]
	#The chance a zombie that has spawned on the surface is riding a horse.
	#Range: 0.0 ~ 1.0
	chanceSurfaceZombieHasHorse = 0.005
	#If enabled, burns zombie horses when daylight shines upon them.
	shouldBurnZombieHorsesInDaylight = false
	#If enabled, a zombie horse with rider will only spawn on the surface.
	onlySpawnZombieHorsesOnSurface = true

