# specialmobs:_family_of_drowned.toml
# This config contains options that apply to the family of drowned as a whole;
# that is, the vanilla replacement and all special variants.


# Category: general
# Options standard to all mob families (that is, not specific to any particular mob family).

	# Whether this mob family replaces vanilla drowned with its vanilla replacement species.
	# The "master_vanilla_replacement" setting in the mod's main config must also be true for this to work.
	# <Boolean> Valid Values: { true, false }, Default: true
	general.vanilla_replacement = true

	# When greater than 0, drowned will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for "master_random_scaling", though
	# species configs can override this value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.family_random_scaling = -1.0

	# The chance for drowned to spawn as special variants.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.25
	general.special_variant_chance.base = 0.25
	# The chance for drowned to spawn as special variants when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: [ "0.13 world_time < 120000", "0.5 moon_phase full & special_difficulty >= 0.5", "0.38 moon_phase full", "0.38 special_difficulty >= 0.5" ]
	#    Range for Values: 0.0 ~ 1.0
	general.special_variant_chance.exceptions = [
		"0.13 world_time < 120000",
		"0.5 moon_phase full & special_difficulty >= 0.5",
		"0.38 moon_phase full",
		"0.38 special_difficulty >= 0.5"
	]

	# The weight of each drowned species to be chosen as the replacement when
	# drowned spawn as special variants. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.abyssal.base = 15.0
	general.weight.brute.base = 60.0
	general.weight.fishing.base = 15.0
	general.weight.frozen.base = 15.0
	general.weight.giant.base = 60.0
	general.weight.hungry.base = 60.0
	general.weight.knight.base = 60.0
	general.weight.plague.base = 60.0

	# The weight of each drowned species to be chosen as the replacement when
	# drowned spawn as special variants when specific environmental conditions are met. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.abyssal.exceptions = []
	general.weight.brute.exceptions = []
	general.weight.fishing.exceptions = []
	general.weight.frozen.exceptions = [
		"7.5 dimension_property ultrawarm",
		"300.0 temp freezing",
		"15.0 temp >= 0.8",
		"7.5 temp > 1.0",
		"300.0 biome minecraft:deep_frozen_ocean",
		"150.0 biome minecraft:cold_ocean",
		"150.0 biome minecraft:deep_cold_ocean",
		"15.0 biome minecraft:lukewarm_ocean",
		"15.0 biome minecraft:deep_lukewarm_ocean",
		"7.5 biome minecraft:warm_ocean",
		"7.5 biome minecraft:deep_warm_ocean"
	]
	general.weight.giant.exceptions = []
	general.weight.hungry.exceptions = []
	general.weight.knight.exceptions = []
	general.weight.plague.exceptions = []
