# specialmobs:_family_of_wither_skeletons.toml
# This config contains options that apply to the family of wither skeletons as a whole;
# that is, the vanilla replacement and all special variants.


# Category: general
# Options standard to all mob families (that is, not specific to any particular mob family).

	# Whether this mob family replaces vanilla wither skeletons with its vanilla replacement species.
	# The "master_vanilla_replacement" setting in the mod's main config must also be true for this to work.
	# <Boolean> Valid Values: { true, false }, Default: true
	general.vanilla_replacement = true

	# When greater than 0, wither skeletons will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for "master_random_scaling", though
	# species configs can override this value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.family_random_scaling = -1.0

	# The chance for wither skeletons to spawn as special variants.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.25
	general.special_variant_chance.base = 0.25
	# The chance for wither skeletons to spawn as special variants when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: [ "0.13 world_time < 120000", "0.5 moon_phase full & special_difficulty >= 0.5", "0.38 moon_phase full", "0.38 special_difficulty >= 0.5" ]
	#    Range for Values: 0.0 ~ 1.0
	general.special_variant_chance.exceptions = [
		"0.13 world_time < 120000",
		"0.5 moon_phase full & special_difficulty >= 0.5",
		"0.38 moon_phase full",
		"0.38 special_difficulty >= 0.5"
	]

	# The weight of each wither skeleton species to be chosen as the replacement when
	# wither skeletons spawn as special variants. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.brute.base = 60.0
	general.weight.gatling.base = 60.0
	general.weight.giant.base = 60.0
	general.weight.knight.base = 60.0
	general.weight.ninja.base = 60.0
	general.weight.sniper.base = 60.0
	general.weight.spitfire.base = 15.0

	# The weight of each wither skeleton species to be chosen as the replacement when
	# wither skeletons spawn as special variants when specific environmental conditions are met. Higher weight is more common.
	# <Number> Range: ≥ 0.0
	general.weight.brute.exceptions = []
	general.weight.gatling.exceptions = []
	general.weight.giant.exceptions = []
	general.weight.knight.exceptions = []
	general.weight.ninja.exceptions = []
	general.weight.sniper.exceptions = []
	general.weight.spitfire.exceptions = []


# Category: wither_skeletons
# Options specific to the family of wither skeletons.

	# Chance for valid wither skeletons to spawn as babies. Baby mobs are about half-sized,
	# move 50% faster, drop 150% more experience, and are 50% cuter.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.05
	wither_skeletons.baby_chance = 0.05
