# deadlyworld:feature_floor_traps.toml
# This config contains options for all floor_trap features specific to the
# 'developer_dimension' dimension from 'bloodnwine2resources'.

	# Entity List fields: General format = [ "namespace:entity_type value1 value2 ...", ... ]
	#   Entity lists are arrays of entity types. Some entity lists specify a number of values linked to each entity type.
	#   Entity types are defined by their key in the entity registry, usually following the pattern 'namespace:entity_name'.
	#   'default' can be used instead of an entity type registry key to provide default values for all entities.
	#   An asterisk '*' can be used to match multiple entity types. For example, 'minecraft:*' will match all vanilla entities.
	#   List entries by default match any entity type derived from (i.e. based on) their entity type. A tilde '~' prefix
	#     disables that extra matching. For example, '~minecraft:zombie'.
	#   There is no real rule for deriving, even in vanilla, but the hope is that mod-added mobs will derive from their base mob.

	# Potion List fields: General format = [ "namespace:effect weight duration amplifier ...", ... ]
	#   Potion lists are arrays of potion effect types. Some potion lists specify a number of values linked to each potion effect.
	#   Potion effects are defined by their key in the effect registry, usually following the pattern 'namespace:effect_name'.
	#   'default' can be used instead of a potion effect registry key to provide default values for all entities.
	#   An asterisk '*' can be used to match multiple potion effects. For example, 'minecraft:*' will match all vanilla effects.
	#   List entries by default match any potion effect derived from (i.e. based on) their potion effect. A tilde '~' prefix
	#     disables that extra matching. For example, '~minecraft:regeneration'.
	#   There is no real rule for deriving, even in vanilla, but the hope is that mod-added mobs will derive from their base mob.


# Category: tnt_floor_trap_features
# Options to customize tnt floor_trap features specific to the
# 'developer_dimension' dimension from 'bloodnwine2resources'.

	# When set to true, places a 1x1 column of glass to the height limit from a few blocks above each
	# generated tnt floor_trap feature. This is game-breaking and laggy. Also prints a message to the console.
	# Consider using a tool to strip away all stone/dirt/etc. or xray after world gen for more intensive testing.
	# <Boolean> Valid Values: { true, false }, Default: false
	tnt_floor_trap_features.testing_markers = false

	# The number of placement attempts per chunk (16x16 blocks) for tnt floor_trap feature
	# A decimal represents a chance for a placement attempt (e.g., 0.3 means 30% chance for one attempt).
	# <Number> Range: ≥ 0.0, Default: 0.16
	tnt_floor_trap_features.placements = 0.16

	# The minimum and maximum (inclusive) heights/y-values tnt floor_trap features can generate at.
	# <Integer> Range: ≥ 0, Default: 12
	tnt_floor_trap_features.height.min = 12
	# <Integer> Range: ≥ 0, Default: 52
	tnt_floor_trap_features.height.max = 52

	# The chance for a chest to generate beneath tnt floor_trap feature.
	# For reference, the loot table for these chests is 'deadlyworld:loot_tables/chests/floor_traps/tnt'.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.3
	tnt_floor_trap_features.chest_chance = 0.3

	# The floor trap is active as long as a player is within this distance (spherical distance).
	# <Number> Range: ≥ 0.0, Default: 6.0
	tnt_floor_trap_features.activation_range = 6.0
	# When the sight check is enabled, tnt floor_trap feature will only activate when they have direct
	# line-of-sight to a player within activation range. The floor trap's delay will continue to tick down,
	# but it will wait to actually activate until it has line-of-sight.
	# <Boolean> Valid Values: { true, false }, Default: true
	tnt_floor_trap_features.activation_sight_check = true

	# The maximum amount of time that must pass before a previously triggered trap resets.
	# <Integer> Range: ≥ 1, Default: 60
	tnt_floor_trap_features.max_reset_time = 60
	# The minimum amount of time that must pass before a previously triggered trap resets.
	# <Integer> Range: ≥ 1, Default: 20
	tnt_floor_trap_features.min_reset_time = 20

	# The maximum fuse time of the TNT spawned by this trap.
	# <Integer> Range: ≥ 1, Default: 180
	tnt_floor_trap_features.max_fuse_time = 180
	# The minimum fuse time of the TNT spawned by this trap.
	# <Integer> Range: ≥ 1, Default: 80
	tnt_floor_trap_features.min_fuse_time = 80

	# The amount of TNT spawned when this trap is activated.
	# <Integer> Range: ≥ 1, Default: 3
	tnt_floor_trap_features.tnt_count = 3
	# The velocity at which the spawned TNT gets launched when this trap activates.
	# <Number> Range: ≥ 0.0, Default: 2.0
	tnt_floor_trap_features.launch_speed = 2.0


# Category: tnt_mob_floor_trap_features
# Options to customize tnt_mob floor_trap features specific to the
# 'developer_dimension' dimension from 'bloodnwine2resources'.

	# When set to true, places a 1x1 column of glass to the height limit from a few blocks above each
	# generated tnt_mob floor_trap feature. This is game-breaking and laggy. Also prints a message to the console.
	# Consider using a tool to strip away all stone/dirt/etc. or xray after world gen for more intensive testing.
	# <Boolean> Valid Values: { true, false }, Default: false
	tnt_mob_floor_trap_features.testing_markers = false

	# The number of placement attempts per chunk (16x16 blocks) for tnt_mob floor_trap feature
	# A decimal represents a chance for a placement attempt (e.g., 0.3 means 30% chance for one attempt).
	# <Number> Range: ≥ 0.0, Default: 0.16
	tnt_mob_floor_trap_features.placements = 0.16

	# The minimum and maximum (inclusive) heights/y-values tnt_mob floor_trap features can generate at.
	# <Integer> Range: ≥ 0, Default: 12
	tnt_mob_floor_trap_features.height.min = 12
	# <Integer> Range: ≥ 0, Default: 52
	tnt_mob_floor_trap_features.height.max = 52

	# The chance for a chest to generate beneath tnt_mob floor_trap feature.
	# For reference, the loot table for these chests is 'deadlyworld:loot_tables/chests/floor_traps/tnt_mob'.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.3
	tnt_mob_floor_trap_features.chest_chance = 0.3

	# The floor trap is active as long as a player is within this distance (spherical distance).
	# <Number> Range: ≥ 0.0, Default: 5.0
	tnt_mob_floor_trap_features.activation_range = 5.0
	# When the sight check is enabled, tnt_mob floor_trap feature will only activate when they have direct
	# line-of-sight to a player within activation range. The floor trap's delay will continue to tick down,
	# but it will wait to actually activate until it has line-of-sight.
	# <Boolean> Valid Values: { true, false }, Default: true
	tnt_mob_floor_trap_features.activation_sight_check = true

	# The maximum amount of time that must pass before a previously triggered trap resets.
	# <Integer> Range: ≥ 1, Default: 60
	tnt_mob_floor_trap_features.max_reset_time = 60
	# The minimum amount of time that must pass before a previously triggered trap resets.
	# <Integer> Range: ≥ 1, Default: 20
	tnt_mob_floor_trap_features.min_reset_time = 20

	# The maximum fuse time of the TNT spawned by this trap.
	# <Integer> Range: ≥ 1, Default: 180
	tnt_mob_floor_trap_features.max_fuse_time = 180
	# The minimum fuse time of the TNT spawned by this trap.
	# <Integer> Range: ≥ 1, Default: 80
	tnt_mob_floor_trap_features.min_fuse_time = 80

	# The amount of TNT spawned when this trap is activated.
	# <Integer> Range: ≥ 1, Default: 3
	tnt_mob_floor_trap_features.tnt_count = 3
	# The velocity at which the spawned TNT gets launched when this trap activates.
	# <Number> Range: ≥ 0.0, Default: 2.0
	tnt_mob_floor_trap_features.launch_speed = 2.0
	# Weighted list of mobs that can be spawned by tnt_mob floor_trap features. One of these is chosen
	# at random when the trap is generated. Traps that are generated as 'dynamic' will pick again
	# between each spawn.
	# <Entity List> Format: [ "namespace:entity_type value", ... ], Default: [ "minecraft:zombie 200", "minecraft:skeleton 100", "minecraft:spider 100", "minecraft:cave_spider 10", "minecraft:creeper 10" ]
	#    Range for Values: ≥ 0
	tnt_mob_floor_trap_features.spawn_list = [
		"minecraft:zombie 200",
		"minecraft:skeleton 100",
		"minecraft:spider 100",
		"minecraft:cave_spider 10",
		"minecraft:creeper 10"
	]

	# The multiplier used when modifying the movement speed of the mobs spawned by this trap.
	# <Number> Range: ≥ 0.0, Default: 1.5
	tnt_mob_floor_trap_features.speed_multiplier = 1.5
	# The multiplier used when modifying the health of the mobs spawned by this trap.
	# <Number> Range: ≥ 0.0, Default: 1.5
	tnt_mob_floor_trap_features.health_multiplier = 1.5


# Category: potion_floor_trap_features
# Options to customize potion floor_trap features specific to the
# 'developer_dimension' dimension from 'bloodnwine2resources'.

	# When set to true, places a 1x1 column of glass to the height limit from a few blocks above each
	# generated potion floor_trap feature. This is game-breaking and laggy. Also prints a message to the console.
	# Consider using a tool to strip away all stone/dirt/etc. or xray after world gen for more intensive testing.
	# <Boolean> Valid Values: { true, false }, Default: false
	potion_floor_trap_features.testing_markers = false

	# The number of placement attempts per chunk (16x16 blocks) for potion floor_trap feature
	# A decimal represents a chance for a placement attempt (e.g., 0.3 means 30% chance for one attempt).
	# <Number> Range: ≥ 0.0, Default: 0.16
	potion_floor_trap_features.placements = 0.16

	# The minimum and maximum (inclusive) heights/y-values potion floor_trap features can generate at.
	# <Integer> Range: ≥ 0, Default: 12
	potion_floor_trap_features.height.min = 12
	# <Integer> Range: ≥ 0, Default: 52
	potion_floor_trap_features.height.max = 52

	# The chance for a chest to generate beneath potion floor_trap feature.
	# For reference, the loot table for these chests is 'deadlyworld:loot_tables/chests/floor_traps/potion'.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.3
	potion_floor_trap_features.chest_chance = 0.3

	# The floor trap is active as long as a player is within this distance (spherical distance).
	# <Number> Range: ≥ 0.0, Default: 5.0
	potion_floor_trap_features.activation_range = 5.0
	# When the sight check is enabled, potion floor_trap feature will only activate when they have direct
	# line-of-sight to a player within activation range. The floor trap's delay will continue to tick down,
	# but it will wait to actually activate until it has line-of-sight.
	# <Boolean> Valid Values: { true, false }, Default: true
	potion_floor_trap_features.activation_sight_check = true

	# The maximum amount of time that must pass before a previously triggered trap resets.
	# <Integer> Range: ≥ 1, Default: 60
	potion_floor_trap_features.max_reset_time = 60
	# The minimum amount of time that must pass before a previously triggered trap resets.
	# <Integer> Range: ≥ 1, Default: 20
	potion_floor_trap_features.min_reset_time = 20
	# Weighted list of potion effects that can be used by potion floor_trap features when hurling splash potions. One of these is chosen
	# at random when the trap is generated. If the trap is generated as 'dynamic' it will pick again
	# between each potion effect.
	# <Potion List> Format: [ "namespace:effect value1 value2 value3", ... ], Default: [ "minecraft:poison 20 200 0", "minecraft:slowness 20 200 1", "minecraft:weakness 20 150 1", "minecraft:instant_damage 20 1 1", "minecraft:hunger 20 500 1" ]
	#    Range for Values: ≥ 0
	potion_floor_trap_features.potion_list = [
		"minecraft:poison 20 200 0",
		"minecraft:slowness 20 200 1",
		"minecraft:weakness 20 150 1",
		"minecraft:instant_damage 20 1 1",
		"minecraft:hunger 20 500 1"
	]


# Category: lava_floor_trap_features
# Options to customize lava floor_trap features specific to the
# 'developer_dimension' dimension from 'bloodnwine2resources'.

	# When set to true, places a 1x1 column of glass to the height limit from a few blocks above each
	# generated lava floor_trap feature. This is game-breaking and laggy. Also prints a message to the console.
	# Consider using a tool to strip away all stone/dirt/etc. or xray after world gen for more intensive testing.
	# <Boolean> Valid Values: { true, false }, Default: false
	lava_floor_trap_features.testing_markers = false

	# The number of placement attempts per chunk (16x16 blocks) for lava floor_trap feature
	# A decimal represents a chance for a placement attempt (e.g., 0.3 means 30% chance for one attempt).
	# <Number> Range: ≥ 0.0, Default: 0.16
	lava_floor_trap_features.placements = 0.16

	# The minimum and maximum (inclusive) heights/y-values lava floor_trap features can generate at.
	# <Integer> Range: ≥ 0, Default: 12
	lava_floor_trap_features.height.min = 12
	# <Integer> Range: ≥ 0, Default: 52
	lava_floor_trap_features.height.max = 52

	# The chance for a chest to generate beneath lava floor_trap feature.
	# For reference, the loot table for these chests is 'deadlyworld:loot_tables/chests/floor_traps/lava'.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.3
	lava_floor_trap_features.chest_chance = 0.3

	# The floor trap is active as long as a player is within this distance (spherical distance).
	# <Number> Range: ≥ 0.0, Default: 4.0
	lava_floor_trap_features.activation_range = 4.0
	# When the sight check is enabled, lava floor_trap feature will only activate when they have direct
	# line-of-sight to a player within activation range. The floor trap's delay will continue to tick down,
	# but it will wait to actually activate until it has line-of-sight.
	# <Boolean> Valid Values: { true, false }, Default: true
	lava_floor_trap_features.activation_sight_check = true

	# The maximum amount of time that must pass before a previously triggered trap resets.
	# <Integer> Range: ≥ 1, Default: 60
	lava_floor_trap_features.max_reset_time = 60
	# The minimum amount of time that must pass before a previously triggered trap resets.
	# <Integer> Range: ≥ 1, Default: 20
	lava_floor_trap_features.min_reset_time = 20
