# specialmobs:undead_witches.toml
# This config contains options that apply only to the undead witch species.


# Category: general
# Options standard to all mob species (that is, not specific to any particular mob species).

	# The chance for undead witches to succeed at natural spawn attempts. Does not affect Mob Replacement.
	# Note: Most species do NOT naturally spawn - they must be added by a mod or data pack for this option to do anything.
	# <Number> Range: 0.0 ~ 1.0, Default: 1.0
	general.natural_spawn_chance.base = 1.0
	# The chance for undead witches to succeed at natural spawn attempts when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: []
	#    Range for Values: 0.0 ~ 1.0
	general.natural_spawn_chance.exceptions = []

	# When greater than 0, undead witches will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for both "master_random_scaling" and
	# "family_random_scaling". The priority is species value > family value > master value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.random_scaling = -1.0

	# Attribute modifiers for undead witches. If no attribute changes are defined here, undead witches
	# will have the exact same attributes as their parent vanilla mob.
	# <Attribute List> Format: [ "namespace:attribute_name operation value", ... ], Default: []
	#    Range for Values: Any Value
	general.attributes = []

	# Subcategory: special_data
	# Special Mob Data. These are the values set to each undead witch on spawn (in their NBT).

		# The amount of experience undead witches drop when killed by a player. Multiplied by 2.5 for babies.
		# Extra experience may drop based on equipment. Slime-style mobs also drop experience equal to slime size.
		# <Integer> Range: ≥ 0, Default: 7
		general.special_data.experience = 7
		# If greater than 0, undead witches will heal 1 half-heart of health every "heal_time" ticks. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 0
		general.special_data.heal_time = 0
		# Fall damage taken by undead witches is multiplied by this value. 0 is fall damage immunity.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.fall_damage_multiplier = 1.0
		# If true, undead witches will take no fire damage. Does not affect spawn restrictions.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fire = false
		# If true, undead witches cannot be set on fire (this setting only matters if not immune to fire).
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_burning = false
		# If true, undead witches can breathe in water.
		# <Boolean> Valid Values: { true, false }, Default: true
		general.special_data.immune_to_drowning = true
		# If true, undead witches will ignore forces applied by flowing fluids.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fluid_push = false
		# If true, undead witches will be continuously damaged while wet.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.sensitive_to_water = false
		# If true, undead witches can be leashed. (Note: Leashed mobs can still attack you.)
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.allow_leashing = false
		# If true, undead witches will not trigger pressure plates.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_pressure_plates = false
		# Undead witches will not be 'trapped' in any blocks specified here (e.g. "cobweb" or "sweet_berry_bush").
		# <"minecraft:block" Registry List> Format: [ "namespace:entry_name", ... ], Default: []
		general.special_data.immune_to_sticky_blocks = []
		# Undead witches cannot be inflicted with any effects specified here (e.g. "instant_damage" or "regeneration").
		# <"minecraft:mob_effect" Registry List> Format: [ "namespace:entry_name", ... ], Default: [ "minecraft:regeneration", "minecraft:poison" ]
		general.special_data.immune_to_effects = [
			"minecraft:regeneration",
			"minecraft:poison"
		]

	# Subcategory: ranged_stats
	# Like Special Mob Data, these are set to NBT on spawn. Unlike SMD, ranged stats are not all applicable to all mobs.

		# The ranged attack spread (inaccuracy) for undead witches. 0 is perfect accuracy.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.ranged_attack.spread = 1.0
		# The walk speed multiplier for undead witches while using their ranged attack AI.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.ranged_attack.walk_speed = 1.0
		# The delay (in ticks) for undead witches to perform a ranged attack from rest. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 60
		general.special_data.ranged_attack.charge_time = 60
		# The maximum distance (in blocks) at which undead witches can use their ranged attacks.
		# 0 disables ranged attacks.
		# <Number> Range: ≥ 0.0, Default: 10.0
		general.special_data.ranged_attack.max_range = 10.0


# Category: undead
# Options specific to undead witches.

	# The minimum and maximum (inclusive) number of times undead witches can summon minions.
	# <Integer> Range: ≥ 0, Default: 3
	undead.summons.min = 3
	# <Integer> Range: ≥ 0, Default: 6
	undead.summons.max = 6
