# specialmobs:wilds_witches.toml
# This config contains options that apply only to the wilds witch species.


# Category: general
# Options standard to all mob species (that is, not specific to any particular mob species).

	# The chance for wilds witches to succeed at natural spawn attempts. Does not affect Mob Replacement.
	# Note: Most species do NOT naturally spawn - they must be added by a mod or data pack for this option to do anything.
	# <Number> Range: 0.0 ~ 1.0, Default: 1.0
	general.natural_spawn_chance.base = 1.0
	# The chance for wilds witches to succeed at natural spawn attempts when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: []
	#    Range for Values: 0.0 ~ 1.0
	general.natural_spawn_chance.exceptions = []

	# When greater than 0, wilds witches will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for both "master_random_scaling" and
	# "family_random_scaling". The priority is species value > family value > master value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.random_scaling = -1.0

	# Attribute modifiers for wilds witches. If no attribute changes are defined here, wilds witches
	# will have the exact same attributes as their parent vanilla mob.
	# <Attribute List> Format: [ "namespace:attribute_name operation value", ... ], Default: [ "minecraft:generic.movement_speed * 0.7" ]
	#    Range for Values: Any Value
	general.attributes = [
		"minecraft:generic.movement_speed * 0.7"
	]

	# Subcategory: special_data
	# Special Mob Data. These are the values set to each wilds witch on spawn (in their NBT).

		# The amount of experience wilds witches drop when killed by a player. Multiplied by 2.5 for babies.
		# Extra experience may drop based on equipment. Slime-style mobs also drop experience equal to slime size.
		# <Integer> Range: ≥ 0, Default: 6
		general.special_data.experience = 6
		# If greater than 0, wilds witches will heal 1 half-heart of health every "heal_time" ticks. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 0
		general.special_data.heal_time = 0
		# Fall damage taken by wilds witches is multiplied by this value. 0 is fall damage immunity.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.fall_damage_multiplier = 1.0
		# If true, wilds witches will take no fire damage. Does not affect spawn restrictions.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fire = false
		# If true, wilds witches cannot be set on fire (this setting only matters if not immune to fire).
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_burning = false
		# If true, wilds witches can breathe in water.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_drowning = false
		# If true, wilds witches will ignore forces applied by flowing fluids.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fluid_push = false
		# If true, wilds witches will be continuously damaged while wet.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.sensitive_to_water = false
		# If true, wilds witches can be leashed. (Note: Leashed mobs can still attack you.)
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.allow_leashing = false
		# If true, wilds witches will not trigger pressure plates.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_pressure_plates = false
		# Wilds witches will not be 'trapped' in any blocks specified here (e.g. "cobweb" or "sweet_berry_bush").
		# <"minecraft:block" Registry List> Format: [ "namespace:entry_name", ... ], Default: [ "minecraft:cobweb" ]
		general.special_data.immune_to_sticky_blocks = [
			"minecraft:cobweb"
		]
		# Wilds witches cannot be inflicted with any effects specified here (e.g. "instant_damage" or "regeneration").
		# <"minecraft:mob_effect" Registry List> Format: [ "namespace:entry_name", ... ], Default: [ "minecraft:poison" ]
		general.special_data.immune_to_effects = [
			"minecraft:poison"
		]

	# Subcategory: ranged_stats
	# Like Special Mob Data, these are set to NBT on spawn. Unlike SMD, ranged stats are not all applicable to all mobs.

		# The ranged attack spread (inaccuracy) for wilds witches. 0 is perfect accuracy.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.ranged_attack.spread = 1.0
		# The walk speed multiplier for wilds witches while using their ranged attack AI.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.ranged_attack.walk_speed = 1.0
		# The delay (in ticks) for wilds witches to perform a ranged attack from rest. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 60
		general.special_data.ranged_attack.charge_time = 60
		# The maximum distance (in blocks) at which wilds witches can use their ranged attacks.
		# 0 disables ranged attacks.
		# <Number> Range: ≥ 0.0, Default: 10.0
		general.special_data.ranged_attack.max_range = 10.0


# Category: wilds
# Options specific to wilds witches.

	# The minimum and maximum (inclusive) number of times wilds witches can summon a spider mount.
	# <Integer> Range: ≥ 0, Default: 1
	wilds.mounts.min = 1
	# <Integer> Range: ≥ 0, Default: 3
	wilds.mounts.max = 3

	# The minimum and maximum (inclusive) number of times wilds witches can summon a spider swarm.
	# <Integer> Range: ≥ 0, Default: 3
	wilds.swarms.min = 3
	# <Integer> Range: ≥ 0, Default: 6
	wilds.swarms.max = 6

	# The minimum and maximum (inclusive) number of spiders wilds witches spawn with each swarm.
	# Note that this is rolled on the summoner's spawn, not each time a swarm is summoned.
	# <Integer> Range: ≥ 0, Default: 3
	wilds.swarm_size.min = 3
	# <Integer> Range: ≥ 0, Default: 4
	wilds.swarm_size.max = 4
