# specialmobs:_normal_zombified_piglins.toml
# This config contains options that apply only to the vanilla replacement zombified piglin species.


# Category: general
# Options standard to all mob species (that is, not specific to any particular mob species).

	# The chance for vanilla replacement zombified piglins to succeed at natural spawn attempts. Does not affect Mob Replacement.
	# Note: Most species do NOT naturally spawn - they must be added by a mod or data pack for this option to do anything.
	# <Number> Range: 0.0 ~ 1.0, Default: 1.0
	general.natural_spawn_chance.base = 1.0
	# The chance for vanilla replacement zombified piglins to succeed at natural spawn attempts when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: []
	#    Range for Values: 0.0 ~ 1.0
	general.natural_spawn_chance.exceptions = []

	# When greater than 0, vanilla replacement zombified piglins will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for both "master_random_scaling" and
	# "family_random_scaling". The priority is species value > family value > master value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.random_scaling = -1.0

	# Attribute modifiers for vanilla replacement zombified piglins. If no attribute changes are defined here, vanilla replacement zombified piglins
	# will have the exact same attributes as their parent vanilla mob.
	# <Attribute List> Format: [ "namespace:attribute_name operation value", ... ], Default: []
	#    Range for Values: Any Value
	general.attributes = []

	# Subcategory: special_data
	# Special Mob Data. These are the values set to each vanilla replacement zombified piglin on spawn (in their NBT).

		# The amount of experience vanilla replacement zombified piglins drop when killed by a player. Multiplied by 2.5 for babies.
		# Extra experience may drop based on equipment. Slime-style mobs also drop experience equal to slime size.
		# <Integer> Range: ≥ 0, Default: 5
		general.special_data.experience = 5
		# If greater than 0, vanilla replacement zombified piglins will heal 1 half-heart of health every "heal_time" ticks. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 0
		general.special_data.heal_time = 0
		# Fall damage taken by vanilla replacement zombified piglins is multiplied by this value. 0 is fall damage immunity.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.fall_damage_multiplier = 1.0
		# If true, vanilla replacement zombified piglins will take no fire damage. Does not affect spawn restrictions.
		# <Boolean> Valid Values: { true, false }, Default: true
		general.special_data.immune_to_fire = true
		# If true, vanilla replacement zombified piglins cannot be set on fire (this setting only matters if not immune to fire).
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_burning = false
		# If true, vanilla replacement zombified piglins can breathe in water.
		# <Boolean> Valid Values: { true, false }, Default: true
		general.special_data.immune_to_drowning = true
		# If true, vanilla replacement zombified piglins will ignore forces applied by flowing fluids.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fluid_push = false
		# If true, vanilla replacement zombified piglins will be continuously damaged while wet.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.sensitive_to_water = false
		# If true, vanilla replacement zombified piglins can be leashed. (Note: Leashed mobs can still attack you.)
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.allow_leashing = false
		# If true, vanilla replacement zombified piglins will not trigger pressure plates.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_pressure_plates = false
		# Vanilla replacement zombified piglins will not be 'trapped' in any blocks specified here (e.g. "cobweb" or "sweet_berry_bush").
		# <"minecraft:block" Registry List> Format: [ "namespace:entry_name", ... ], Default: []
		general.special_data.immune_to_sticky_blocks = []
		# Vanilla replacement zombified piglins cannot be inflicted with any effects specified here (e.g. "instant_damage" or "regeneration").
		# <"minecraft:mob_effect" Registry List> Format: [ "namespace:entry_name", ... ], Default: [ "minecraft:regeneration", "minecraft:poison" ]
		general.special_data.immune_to_effects = [
			"minecraft:regeneration",
			"minecraft:poison"
		]

	# Subcategory: ranged_stats
	# Like Special Mob Data, these are set to NBT on spawn. Unlike SMD, ranged stats are not all applicable to all mobs.

		# The base ranged attack damage for vanilla replacement zombified piglins (in half-hearts).
		# <Number> Range: ≥ 0.0, Default: 2.0
		general.special_data.ranged_attack.damage = 2.0
		# The ranged attack spread (inaccuracy) for vanilla replacement zombified piglins. 0 is perfect accuracy.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.ranged_attack.spread = 1.0
		# The walk speed multiplier for vanilla replacement zombified piglins while using their ranged attack AI.
		# <Number> Range: ≥ 0.0, Default: 0.8
		general.special_data.ranged_attack.walk_speed = 0.8
		# The delay (in ticks) for vanilla replacement zombified piglins to perform a ranged attack from rest. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 20
		general.special_data.ranged_attack.charge_time = 20
		# The maximum distance (in blocks) at which vanilla replacement zombified piglins can use their ranged attacks.
		# 0 disables ranged attacks.
		# <Number> Range: ≥ 0.0, Default: 15.0
		general.special_data.ranged_attack.max_range = 15.0


# Category: zombified_piglins
# Options standard to all zombified piglins.

	# Chance for vanilla replacement zombified piglins to spawn with a bow, which enables their ranged attack (if max range > 0).
	# <Number> Range: 0.0 ~ 1.0, Default: 0.2
	zombified_piglins.bow_chance = 0.2

	# Chance for vanilla replacement zombified piglins to spawn with a shield if they did not spawn with a bow.
	# Shield users have a 33% chance to block frontal attacks (100% vs. long range attacks) and can be broken by axes.
	# <Number> Range: 0.0 ~ 1.0, Default: 0.05
	zombified_piglins.shield_chance = 0.05
