# specialmobs:wildfire_blazes.toml
# This config contains options that apply only to the wildfire blaze species.


# Category: general
# Options standard to all mob species (that is, not specific to any particular mob species).

	# The chance for wildfire blazes to succeed at natural spawn attempts. Does not affect Mob Replacement.
	# Note: Most species do NOT naturally spawn - they must be added by a mod or data pack for this option to do anything.
	# <Number> Range: 0.0 ~ 1.0, Default: 1.0
	general.natural_spawn_chance.base = 1.0
	# The chance for wildfire blazes to succeed at natural spawn attempts when specific environmental conditions are met.
	# <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: []
	#    Range for Values: 0.0 ~ 1.0
	general.natural_spawn_chance.exceptions = []

	# When greater than 0, wildfire blazes will have a random render scale applied. This is a visual effect only.
	# If this is set to a non-negative value, it overrides the value set for both "master_random_scaling" and
	# "family_random_scaling". The priority is species value > family value > master value.
	# <Number> Range: -1.0 ~ 1.0, Default: -1.0
	general.random_scaling = -1.0

	# Attribute modifiers for wildfire blazes. If no attribute changes are defined here, wildfire blazes
	# will have the exact same attributes as their parent vanilla mob.
	# <Attribute List> Format: [ "namespace:attribute_name operation value", ... ], Default: [ "minecraft:generic.max_health + 20.0" ]
	#    Range for Values: Any Value
	general.attributes = [
		"minecraft:generic.max_health + 10.0"
	]

	# Subcategory: special_data
	# Special Mob Data. These are the values set to each wildfire blaze on spawn (in their NBT).

		# The amount of experience wildfire blazes drop when killed by a player. Multiplied by 2.5 for babies.
		# Extra experience may drop based on equipment. Slime-style mobs also drop experience equal to slime size.
		# <Integer> Range: ≥ 0, Default: 12
		general.special_data.experience = 12
		# If greater than 0, wildfire blazes will heal 1 half-heart of health every "heal_time" ticks. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 40
		general.special_data.heal_time = 40
		# Fall damage taken by wildfire blazes is multiplied by this value. 0 is fall damage immunity.
		# <Number> Range: ≥ 0.0, Default: 1.0
		general.special_data.fall_damage_multiplier = 1.0
		# If true, wildfire blazes will take no fire damage. Does not affect spawn restrictions.
		# <Boolean> Valid Values: { true, false }, Default: true
		general.special_data.immune_to_fire = true
		# If true, wildfire blazes cannot be set on fire (this setting only matters if not immune to fire).
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_burning = false
		# If true, wildfire blazes can breathe in water.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_drowning = false
		# If true, wildfire blazes will ignore forces applied by flowing fluids.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_fluid_push = false
		# If true, wildfire blazes will be continuously damaged while wet.
		# <Boolean> Valid Values: { true, false }, Default: true
		general.special_data.sensitive_to_water = true
		# If true, wildfire blazes can be leashed. (Note: Leashed mobs can still attack you.)
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.allow_leashing = false
		# If true, wildfire blazes will not trigger pressure plates.
		# <Boolean> Valid Values: { true, false }, Default: false
		general.special_data.immune_to_pressure_plates = false
		# Wildfire blazes will not be 'trapped' in any blocks specified here (e.g. "cobweb" or "sweet_berry_bush").
		# <"minecraft:block" Registry List> Format: [ "namespace:entry_name", ... ], Default: []
		general.special_data.immune_to_sticky_blocks = []
		# Wildfire blazes cannot be inflicted with any effects specified here (e.g. "instant_damage" or "regeneration").
		# <"minecraft:mob_effect" Registry List> Format: [ "namespace:entry_name", ... ], Default: []
		general.special_data.immune_to_effects = []

	# Subcategory: ranged_stats
	# Like Special Mob Data, these are set to NBT on spawn. Unlike SMD, ranged stats are not all applicable to all mobs.

		# The ranged attack spread (inaccuracy) for wildfire blazes. 0 is perfect accuracy.
		# <Number> Range: ≥ 0.0, Default: 0.1
		general.special_data.ranged_attack.spread = 0.1
		# The delay (in ticks) for wildfire blazes to perform a ranged attack from rest. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 30
		general.special_data.ranged_attack.charge_time = 30
		# The total delay (in ticks) wildfire blazes wait between each ranged attack. (20 ticks = 1 second)
		# <Integer> Range: ≥ 0, Default: 80
		general.special_data.ranged_attack.refire_time = 80
		# The maximum distance (in blocks) at which wildfire blazes can use their ranged attacks.
		# 0 disables ranged attacks.
		# <Number> Range: ≥ 0.0, Default: 20.0
		general.special_data.ranged_attack.max_range = 20.0


# Category: blazes
# Options standard to all blazes.

	# The number of fireballs wildfire blazes launch with each burst.
	# <Integer> Range: ≥ 0, Default: 1
	blazes.fireball_attack.burst_count = 1
	# The time (in ticks) wildfire blazes wait between each fireball in a burst. (20 ticks = 1 second)
	# <Integer> Range: ≥ 0, Default: 0
	blazes.fireball_attack.burst_delay = 0


# Category: wildfire
# Options specific to wildfire blazes.

	# The minimum and maximum (inclusive) number of babies wildfire blazes spawn on death.
	# <Integer> Range: ≥ 0, Default: 3
	wildfire.babies.min = 3
	# <Integer> Range: ≥ 0, Default: 6
	wildfire.babies.max = 6

	# The minimum and maximum (inclusive) number of times wildfire blazes can summon minions.
	# <Integer> Range: ≥ 0, Default: 4
	wildfire.summons.min = 4
	# <Integer> Range: ≥ 0, Default: 10
	wildfire.summons.max = 10
